<div class="pt-1">
    <div class="row pt-1">
        <div class="col-12">
            <b><?php echo $this->data['filter']->getDisplayName(); ?></b>
        </div>
    </div>
    <div class="row pt-1">
        <div class="col-2">From</div>
        <div class="col-10">
            <input type="date"
                   name="<?php echo $this->data['filter']->getName(); ?>[min]"
                   value="<?php echo str_replace('\'', '', $this->data['filter']->getMin()); ?>"
            />
        </div>
    </div>
    <div class="row pt-1">
        <div class="col-2">To</div>
        <div class="col-10">
            <input type="date"
                   name="<?php echo $this->data['filter']->getName(); ?>[max]"
                   value="<?php echo str_replace('\'', '', $this->data['filter']->getMax()); ?>"
            />
        </div>
    </div>
</div>
