<div class="p-1">
    <div class="row">
        <div class="col-12">
            <b><?php echo $this->data['filter']->getDisplayName(); ?></b>
        </div>
    </div>
    <div class="row p-1">
        <div class="col-2">Name</div>
        <div class="col-10">
            <input type="text"
                   name="<?php echo $this->data['filter']->getName(); ?>[min]"
                   value="<?php echo $this->data['filter']->getMin(); ?>"
            />
        </div>
    </div>
</div>
