version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php_app
    volumes:
      - ./../recruitment-task/:/var/www/recruitment-task/

  webserver:
    image: nginx:latest
    container_name: nginx_server
    depends_on:
      - app
    volumes:
      - ./../recruitment-task/:/var/www/recruitment-task/
      - ./../recruitment-task/build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  db:
    container_name: recruitment-task-db
    image: postgres:15
    environment:
      POSTGRES_DB: recruitment_task
      POSTGRES_USER: recruitment_task
      POSTGRES_PASSWORD: recruitment_task
    volumes:
      - ./../recruitment-task/postgres/data:/var/lib/postgresql/data
      - ./../recruitment-task/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db_data:
