<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo $this->data['title']; ?></title>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/v/bs4-4.6.0/jq-3.7.0/dt-2.1.8/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="https://cdn.datatables.net/v/bs4-4.6.0/jq-3.7.0/dt-2.1.8/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>

</head>
<body>
<div class="row">
    <div class="col-8 mx-auto">
        <?php $this->partial('dashboard/index.phtml'); ?>
    </div>
</div>
<div class="row">
    <div class="col-8 mx-auto">
        <h1><?php echo $this->data['title']; ?></h1>
    </div>
</div>
<?php if (!empty($this->data['filterBuilder'])): ?>
    <?php $this->partial('filter/filter.phtml', $this->data); ?>
<?php endif; ?>
<table id="example" class="table table-striped table-bordered">
    <thead class="thead-dark">
    <tr>
        <th scope="col">#</th>
        <?php foreach ($this->data['columns'] as $column): ?>
            <th scope="col"><?php echo $column; ?></th>
        <?php endforeach; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->data['rows'] as $index => $row): ?>
        <tr>
            <th scope="row"><?php echo $index + 1 ?></th>
            <?php foreach ($this->data['columns'] as $key => $column): ?>
                <td><?php echo $row[$key]; ?></td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script>
    new DataTable('#example');
</script>
</body>
</html>